# Generated by Django 5.1.3 on 2024-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_table_vote_ratio_table_vote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='feature',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
